# Generated by Django 6.0.2 on 2026-03-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_application_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
