# Generated by Django 6.0.2 on 2026-03-15 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_application_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeker_name', models.CharField(max_length=255)),
                ('seeker_email', models.EmailField(max_length=254)),
                ('reason', models.CharField(max_length=255)),
                ('withdrawn_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_logs', to='jobs.job')),
            ],
        ),
    ]
